spring:
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: 1
      properties:
        "[spring.json.type.mapping]": foo:org.example.common.Foo1,bar:org.example.common.Bar1
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      enable-auto-commit: false
    bootstrap-servers: 10.0.24.133:9092