server:
  port: 8080
  tomcat:
    max-swallow-size: -1
  error:
    include-exception: true
    include-stacktrace: ALWAYS
    include-message: ALWAYS
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*
spring:
  shardingsphere:
    enabled: true
    datasource:
      #指定数据源 名称可以自定义，注意：名称要跟后面的配置一致
      names: ds0
      #配置数据源的连接信息
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
        username: root
        password: root
    rules:
      sharding:
        default-data-source-name: ds0
        props:
          #是否输出sql
          sql-show: true
        #绑定表规则列表,多个以逗号分割
        binding-tables[0]: device_data
        tables:
          device_data:
            actual-data-nodes: ds0.device_data_$->{2024..2099}0$->{1..9},ds0.device_data_$->{2023..2099}$->{10..12},ds0.device_data_20230$->{7..9}
            table-strategy:
              standard:
                sharding-column: create_time
                sharding-algorithm-name: std_interval
            key-generate-strategy:
              column: id
              key-generator-name: snowflake
        #分库或者分表算法配置
        sharding-algorithms:
          #device_pass_record分表算法配置
          std_interval:
            type: INTERVAL
            props:
              datetime-pattern: 'yyyy-MM-dd HH:mm:ss'
              datetime-lower: '2000-08-15 00:00:00'
              datetime-upper: '2099-08-15 00:00:00'
              sharding-suffix-pattern: yyyyMM
              datetime-interval-unit: MONTHS
#mybatis plus 设置
mybatis-plus:
  mapper-locations: classpath*:/org/test/mapper/xml/*Mapper.xml
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      #主键类型  0:"数据库ID自增",1:"该类型为未设置主键类型", 2:"用户输入ID",3:"全局唯一ID (数字类型唯一ID)", 4:"全局唯一ID UUID",5:"字符串全局唯一ID (idWorker 的字符串表示)";
      id-type: ASSIGN_ID
      # 默认数据库表下划线命名
      table-underline: true
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 返回类型为Map,显示null对应的字段
    call-setters-on-nulls: true